### ISSUE TITLE
[Bug] Docker build failures

### ISSUE THREAD

**Issue by hlydecker** [GPlates/pygplates-tutorials#4]
I'm trying to follow the suggested installation and am running into issues.

**My system:**
- macOS Big Sur 11.6.4
- Intel CPU
- Docker version 20.10.12

**What I did:**

After cloning the repository and navigating into the docker directory, I ran

```bash
docker build -t gplates/pygplates-tutorials .
```

**My error:**
![image](https://user-images.githubusercontent.com/50643975/172532846-5b7bc842-1cac-4370-8a49-795063a73982.png)

**Comment by michaelchin** [comment]
This is because cartopy requires Proj 8, but the version of Proj in Ubuntu 20.04 is 6.3.
1. we have a old docker image on docker hub, you may try `docker pull gplates/pygplates-tutorials` and use the old image.
2. you may try to modify this file https://github.com/GPlates/pygplates-tutorials/blob/master/docker/Dockerfile and use Ubuntu 22.04

**Comment by hlydecker** [comment]
Thanks for the quick response @michaelchin! I'll try out those options and update you with how it goes.

**Comment by michaelchin** [comment]
> Thanks for the quick response @michaelchin! I'll try out those options and update you with how it goes.

if you try option 2, you also need to get the pygplates for Ubuntu 22.04 from https://www.earthbyte.org/download-pygplates-0-36/

**Comment by hlydecker** [comment]
Option 1 worked fine; weirdly I had tried that before but it was failing but when I tried it again it works and I can use all the notebooks. thanks for the help :)
