### ISSUE TITLE
Missing plate-tectonics-and-earthquakes.ipynb notebook?

### ISSUE THREAD

**Issue by nkinar** [GPlates/pygplates-tutorials#5]
What happened to the plate-tectonics-and-earthquakes.ipynb notebook?  I would like to use the notebook offline as a student activity, but I can only find the notebook on the website and not in the repo.

**Comment by michaelchin** [comment]
There is a copy here https://github.com/EarthByte/miscellaneous-notebooks/blob/master/notebooks/plate-tectonics-and-earthquakes.ipynb

**Comment by nkinar** [comment]
Thanks for the fast response!  I will clone the other repo, but any chance to have the notebook added to the notebooks folder in this repo as it is listed in the readme information?  I've been trying to copy in the plate-tectonics-and-earthquakes.ipynb notebook to the directory that I cloned from this repo, but when running some of the cells, I received an error related to not being able to find some shapefiles.

**Comment by michaelchin** [comment]
The notebook was moved out of this repository for a reason. But I cannot remember what the reason was. It has been a while.

All the data is here https://github.com/EarthByte/miscellaneous-notebooks/tree/master/data

You might need to change this line(see the link below) or create a symbolic link to the data folder.

https://github.com/EarthByte/miscellaneous-notebooks/blob/bedffc4d63f3c7d9c0c3cbc6b9c605a6493e7fd8/libs/tut.py#L15

**Comment by michaelchin** [comment]
This is the symbolic link  which I was talking about in the previous comment https://github.com/GPlates/pygplates-tutorials/blob/master/notebooks/Data

You need to do the same in the other repository.

**Comment by nkinar** [comment]
That is awesome!  Thanks @michaelchin.  I will make a symbolic link and also test the two repos.  Many thanks for your help.
